# azure-pipelines.yml

trigger:
  branches:
    include:
      - main # Replace with your branch name

pool:
  vmImage: 'ubuntu-latest' # The type of agent to run the pipeline on

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.x' # Replace with your .NET version
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: dotnet build --configuration Release
      displayName: 'Build project'

- stage: Test
  jobs:
  - job: TestJob
    steps:
    - script: dotnet test --configuration Release
      displayName: 'Run tests'

- stage: Deploy
  jobs:
  - job: DeployJob
    steps:
    - script: echo "Deploying application..."
      displayName: 'Deploy'